version: '3.10'

services:

  db:
    image: postgres:14
    container_name: mlflow_postgres
    volumes: 
      - ./db_data/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=mlflow_db
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow_meme
    ports:
      - 5000:5432
    networks:
      - mlflow_net

  s3:
    image: minio/minio
    container_name: mlflow_s3
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ACCESS_KEY: mlflow
      MINIO_SECRET_KEY: mlflow_meme
    command: server /data --console-address ":9001"
    networks:
      - mlflow_net



  server:
    image: mlflow_server
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: mlflow_server
    ports:
      - 8118:8118
    command: mlflow ui --backend-store-uri postgresql://mlflow:mlflow_meme@host.docker.internal:5000/mlflow_db --default-artifact-root S3:/mlflow --host 0.0.0.0 --port 8118
    volumes: 
      - .:/code
    depends_on: 
      - db
    networks:
      - mlflow_net



networks:
  mlflow_net:
    driver: bridge
    name: mlflow_net
